services:
  server:
    image: "swiftlang/swift:nightly-focal"
    volumes:
      - /Users/prasadrajalingamgari/Documents/Winter_Term/SE:/code
    ports:
      - "3000:3000"
    environment:
      - USER=prasadrajalingamgari
    # command: bash -c "apt-get update && apt-get install nodejs && node /Users/prasadrajalingamgari/Documents/Winter_Term/SE/app.js"
    

  swift-client:
    image: "swiftlang/swift:nightly-focal"
    volumes:
      - /Users/prasadrajalingamgari/Documents/Winter_Term/SE:/code
    environment:
      - USER=prasadrajalingamgari


  rust-client:
    image: "library/rust:latest"
    volumes:
      - /Users/prasadrajalingamgari/Documents/Winter_Term/SE:/code
    environment:
      - USER=prasadrajalingamgari
      
    

